# Generated by Django 3.2.20 on 2023-12-11 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudgetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_json_string', models.TextField(default='{"default": {}, "list_set": []}')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MonthlyBookSetting_ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Category_Correlation',
            fields=[
                ('company_accountname', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('company_commonname', models.CharField(blank=True, max_length=250)),
                ('category_hook', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyNickNameBookSetting_ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_json_string', models.TextField(default='{"\\uc218\\uc785": ["\\uae09\\uc5ec\\uc18c\\ub4dd", "\\uc6a9\\ub3c8", "\\uae08\\uc735\\uc18c\\ub4dd"], "\\uc18c\\ube44": ["\\uc2dd\\ube44", "\\uc8fc\\uac70\\ube44", "\\ud1b5\\uc2e0\\ube44", "\\uc0dd\\ud65c\\ube44", "\\ubbf8\\uc6a9\\ube44", "\\uc758\\ub8cc\\ube44", "\\ubb38\\ud654\\ube44", "\\uad50\\ud1b5\\ube44", "\\uc138\\uae08", "\\uce74\\ub4dc\\ub300\\uae08", "\\ubcf4\\ud5d8", "\\uae30\\ud0c0"], "\\uc774\\uccb4": ["\\ub0b4\\uacc4\\uc88c\\uc774\\uccb4", "\\uacc4\\uc88c\\uc774\\uccb4", "\\uc800\\ucd95", "\\ud22c\\uc790"]}')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CategorySetting_ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
