# Generated by Django 4.1.5 on 2023-04-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Category_Correlation',
            fields=[
                ('company_accountname', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('company_commonname', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_category', models.CharField(max_length=50)),
                ('main_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Category',
            fields=[
                ('sub_category', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('upper_clas_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='acc_record.main_category', verbose_name='category_id')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('transaction_time', models.DateTimeField()),
                ('deposit_amount', models.IntegerField(default=0)),
                ('withdrawal_amount', models.IntegerField(default=0)),
                ('main_category', models.CharField(default='미지정', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('sub_category', models.ManyToManyField(blank=True, to='acc_record.tag_category')),
                ('transaction_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='financial_account.financialaccount')),
                ('transaction_from_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='financial_account.cardaccount')),
                ('transaction_to_name', models.ForeignKey(blank=True, default='현금', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='acc_record.company_category_correlation')),
            ],
        ),
        migrations.AddField(
            model_name='company_category_correlation',
            name='category_hook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooked_company', to='acc_record.main_category', verbose_name='category_id'),
        ),
    ]
