# Generated by Django 3.2.20 on 2023-12-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_to_name',
        ),
        migrations.DeleteModel(
            name='Company_Category_Correlation',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
    ]
