# Generated by Django 3.2 on 2023-02-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0001_initial'),
        ('acc_record', '0002_transaction_transaction_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category_hooked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hookedtransaction', to='acc_record.flow_category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='financial_account.financialaccount'),
        ),
    ]
