# Generated by Django 3.2 on 2023-03-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0003_auto_20230226_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_from',
        ),
    ]
