# Generated by Django 3.2 on 2023-03-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0003_cardaccount_bankconnect'),
        ('acc_record', '0004_remove_transaction_transaction_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='financial_account.financialaccount'),
        ),
    ]
