# Generated by Django 3.2 on 2023-03-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0018_auto_20230320_0115'),
        ('acc_record', '0005_transaction_transaction_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='financial_account.cardaccount'),
        ),
    ]
