# Generated by Django 3.2 on 2023-03-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0006_transaction_transaction_from_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Category_Correlation',
            fields=[
                ('compnay_accoutname', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('company_commonname', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_category', models.CharField(max_length=50)),
                ('main_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Category',
            fields=[
                ('sub_category', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('upper_clas_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='acc_record.main_category', verbose_name='category_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category_hooked',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_to_nickname',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Flow_category',
        ),
        migrations.AddField(
            model_name='company_category_correlation',
            name='category_hook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooked_company', to='acc_record.main_category', verbose_name='category_id'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='acc_record.Tag_Category'),
        ),
    ]
