# Generated by Django 3.2 on 2023-03-28 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0007_auto_20230328_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_to_name_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='acc_record.company_category_correlation'),
        ),
    ]
