# Generated by Django 3.2 on 2023-03-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0008_transaction_transaction_to_name_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_category_correlation',
            old_name='compnay_accoutname',
            new_name='company_accoutname',
        ),
    ]
