# Generated by Django 3.2 on 2023-03-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0009_rename_compnay_accoutname_company_category_correlation_company_accoutname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_category_correlation',
            old_name='company_accoutname',
            new_name='company_accountname',
        ),
    ]
