# Generated by Django 3.2 on 2023-04-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0011_alter_transaction_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_to_name_related',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_to_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='acc_record.company_category_correlation'),
        ),
    ]
