# Generated by Django 3.2 on 2023-04-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0012_auto_20230401_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='changed_amount',
            new_name='deposit_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_amount',
            field=models.IntegerField(default=0),
        ),
    ]
