# Generated by Django 3.2 on 2023-04-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0013_auto_20230404_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_to_name',
            field=models.ForeignKey(blank=True, default='현금', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='acc_record.company_category_correlation'),
        ),
    ]
