# Generated by Django 3.2 on 2023-04-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0014_alter_transaction_transaction_to_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Tag_Category',
        ),
    ]
