# Generated by Django 3.2 on 2023-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0015_auto_20230424_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Category',
            fields=[
                ('sub_category', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
