# Generated by Django 3.2 on 2023-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0016_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='acc_record.Tag_Category'),
        ),
    ]
