# Generated by Django 3.2 on 2023-04-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_record', '0017_transaction_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='transaction', to='acc_record.Tag_Category'),
        ),
    ]
