# Generated by Django 4.2.1 on 2023-06-18 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cardaccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=250)),
                ("corpname", models.CharField(max_length=20)),
                ("cardnumber", models.CharField(max_length=50)),
                ("card_type", models.CharField(default="체크카드", max_length=50)),
                ("expiredmonth", models.DateField(default=datetime.date.today)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Financialaccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=250)),
                ("bankname", models.CharField(max_length=20)),
                ("accountnumber", models.CharField(max_length=100)),
                ("account_type", models.CharField(default="입출금계좌", max_length=50)),
                (
                    "account_founddate",
                    models.DateField(default=datetime.date(2016, 1, 1)),
                ),
                ("account_expireddate", models.DateField(blank=True, null=True)),
                ("assetamount", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Payaccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=250)),
                ("corpname", models.CharField(max_length=20)),
                ("assetamount", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "bankconnection",
                    models.ManyToManyField(
                        blank=True,
                        related_name="connectpay",
                        to="financial_account.financialaccount",
                    ),
                ),
                (
                    "cardconnection",
                    models.ManyToManyField(
                        blank=True,
                        related_name="connectpay",
                        to="financial_account.cardaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cardaccount",
            name="bankconnect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connectcard",
                to="financial_account.financialaccount",
            ),
        ),
    ]
