# Generated by Django 3.2 on 2023-03-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='accountnumber',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
