# Generated by Django 3.2.20 on 2023-11-25 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardaccount',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Card_ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Account_ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payaccount',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Payment_ownership', to=settings.AUTH_USER_MODEL),
        ),
    ]
