# Generated by Django 3.2 on 2023-03-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0002_auto_20230305_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardaccount',
            name='bankconnect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectcard', to='financial_account.financialaccount'),
        ),
    ]
