# Generated by Django 3.2 on 2023-03-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0003_cardaccount_bankconnect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='cardaccount',
            name='cardnumber',
            field=models.CharField(default='none', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
