# Generated by Django 3.2 on 2023-03-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0004_auto_20230306_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='payaccount',
            name='bankconnection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectpay', to='financial_account.financialaccount'),
        ),
        migrations.AddField(
            model_name='payaccount',
            name='cardconnection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectpay', to='financial_account.cardaccount'),
        ),
        migrations.AlterField(
            model_name='cardaccount',
            name='cardnumber',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
