# Generated by Django 3.2 on 2023-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0006_auto_20230306_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='assetamount',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(default='입출금계좌', max_length=50),
        ),
    ]
