# Generated by Django 3.2 on 2023-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0008_financialaccount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardaccount',
            name='card_type',
            field=models.CharField(default='체크카드', max_length=50),
        ),
    ]
