# Generated by Django 3.2 on 2023-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0009_cardaccount_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='assetamount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
