# Generated by Django 3.2 on 2023-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0011_alter_financialaccount_assetamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payaccount',
            name='assetamount',
            field=models.IntegerField(default=0),
        ),
    ]
