# Generated by Django 3.2 on 2023-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0012_alter_payaccount_assetamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payaccount',
            name='bankconnection',
            field=models.ManyToManyField(blank=True, related_name='connectpay', to='financial_account.Financialaccount'),
        ),
        migrations.AlterField(
            model_name='payaccount',
            name='cardconnection',
            field=models.ManyToManyField(blank=True, related_name='connectpay', to='financial_account.Cardaccount'),
        ),
    ]
