# Generated by Django 3.2 on 2023-03-16 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0013_auto_20230316_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardaccount',
            name='expiredmonth',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
