# Generated by Django 3.2 on 2023-03-21 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0018_auto_20230320_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardaccount',
            name='expiredmonth',
            field=models.DateField(default=datetime.date(2023, 3, 21)),
        ),
    ]
