# Generated by Django 4.2.1 on 2023-06-18 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("financial_account", "0032_alter_cardaccount_expiredmonth"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
