# Generated by Django 3.2.20 on 2023-12-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBookSetting',
        ),
    ]
