# Generated by Django 3.2 on 2023-05-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyBookSettings',
            new_name='MonthlyBookSetting',
        ),
    ]
